# Generated by Django 4.1.4 on 2023-01-01 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport_articles', '0001_initial'),
        ('transport_order_articles', '0001_initial'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportarticle',
            name='transport_order_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_order_articles.transportorderarticle'),
        ),
        migrations.AddField(
            model_name='transportarticle',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouses.warehouse'),
        ),
    ]
