# Generated by Django 4.1.4 on 2022-12-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('serial', models.CharField(max_length=200)),
                ('unit', models.CharField(choices=[('Kg', 'Kg'), ('gr', 'gr'), ('T', 'T')], default='Kg', max_length=10)),
                ('weight', models.PositiveIntegerField(null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
