# Generated by Django 4.1.4 on 2023-01-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_order_articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportorderarticle',
            name='transport_quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
