# Generated by Django 4.1.4 on 2023-01-01 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(max_length=200)),
                ('parent_id', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('1', 'Pending'), ('2', 'Prepared'), ('3', 'Taken'), ('4', 'In Transport'), ('5', 'Arrived'), ('6', 'Completed')], default='1', max_length=2)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.transport')),
            ],
        ),
    ]
