# Generated by Django 4.1.4 on 2023-01-01 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0001_initial'),
        ('transport_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportorder',
            name='transport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transports.transport'),
        ),
    ]
