# Generated by Django 4.1.4 on 2022-12-31 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regals', '0001_initial'),
        ('regal_positions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regalposition',
            name='regal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regals.regal'),
        ),
    ]
